config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get '/about', to: 'about#index'
  get '/search', to: "search#index"
  
  get '/admin', to: 'home#aindex'
  get '/userhome', to: 'home#uindex'
  get '/your-quotes', to: 'home#uquotes'

  # session routes
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :quote_categories
  resources :quotes
  resources :authors
  resources :categories
  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

end

app/models/quote.rb
class Quote < ApplicationRecord
  belongs_to :user
  belongs_to :author
  has_many :quote_categories, dependent: :destroy
  has_many :categories, through: :quote_categories
  accepts_nested_attributes_for :quote_categories, reject_if: :all_blank, allow_destroy: true

end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  before_action :set_quote, only: %i[ show edit update destroy ]
  before_action :require_login, except: [ :show]

  # GET /quotes or /quotes.json
  def index
    @quotes = current_user.quotes
  end

  # GET /quotes/1 or /quotes/1.json
  def show
    if logged_in? #if there is an active session
      if current_user.id == @quote.user_id #if current user is the uploader, grant access (by doing nothing).
      else #if current user is not the uploader, deny access and return to launch page
        flash[:error] = "You are not authorised to access this resource"
        redirect_to userhome_path
      end
    else #if there is not an active session
      flash[:error] = "you are not authorised to access this resource"
      redirect_to login_path
    end
  end

  # GET /quotes/new
  def new
    @quote = Quote.new
    8.times {@quote.quote_categories.build} #builds 8 quote category fields
  end

  # GET /quotes/1/edit
  def edit
    if logged_in? #if there is an active session
      if current_user.id == @quote.user_id #if current user is the uploader, grant access (by doing nothing).
      else #if current user is not the uploader, deny access and return to launch page
        flash[:error] = "You are not authorised to access this resource"
        redirect_to userhome_path
      end
    else #if there is not an active session
      flash[:error] = "you are not authorised to access this resource"
      redirect_to login_path
    end
  end

  # POST /quotes or /quotes.json
  def create
    @quote = Quote.new(quote_params)

    respond_to do |format|
      if @quote.save
        format.html { redirect_to quote_url(@quote), notice: "Quote was successfully created." }
        format.json { render :show, status: :created, location: @quote }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /quotes/1 or /quotes/1.json
  def update
    respond_to do |format|
      if @quote.update(quote_params)
        format.html { redirect_to quote_url(@quote), notice: "Quote was successfully updated." }
        format.json { render :show, status: :ok, location: @quote }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quotes/1 or /quotes/1.json
  def destroy
    @quote.destroy

    respond_to do |format|
      format.html { redirect_to quotes_url, notice: "Quote was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quote
      @quote = Quote.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def quote_params
      params.require(:quote).permit(:quoteText, :yearOfPublication, :comment, :isQuotePublic, :user_id, :author_id, quote_categories_attributes: [:id, :category_id])
    end
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/views/quotes/_form.html.erb
<%= form_with(model: quote) do |form| %>
  <% if @quote.errors.any? %>
    <div class="alert alert-danger">
      <ul>
        <% @quote.errors.full_message.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form_with(model: @quote, url: quotes_path, method: :post, local: true) do |form| %>
    <!-- getting user id of the form from the session, should be inaccessible for logged out users -->
    <%= form.hidden_field :user_id, value: current_user.id %>

    <!-- non-hidden form fields, rendered using Bootstrap -->
    <div class="form-group" style="padding-bottom: 10px;">
      <%= form.text_field :quoteText, placeholder: 'Enter quote here', class: 'form-control' %>
    </div>
    <!-- handling authors -->
    <div class "form-group" style="padding-bottom: 10px">
      <%= form.label :author_id, "Author", class: "form-label d-inline-block me-2" %>
      <%= form.select :author_id, Author.all.collect {|auth| [auth.authName, auth.id]}, {include_blank: true}, class: "form-control d-inline-block" %>
    </div>
    <div class="form-group" style="padding-bottom: 10px;">
      <%= form.text_field :yearOfPublication, placeholder: 'Enter publication year (if known)', class: 'form-control' %>
    </div>
    <div class="form-group" style="padding-bottom: 10px;">
      <%= form.text_field :comment, placeholder: 'Enter comment (optional)', class: 'form-control' %>
    </div>
    <div class="form-group" style="padding-bottom: 10px;">
      <%= form.label :isQuotePublic do %>
      Public
        <%= form.check_box :isQuotePublic, class: "form-check-input" %>
      <% end %>
    </div>

    <!-- handling quote categories -->
    <div id="categories-container">
        <% @quote.quote_categories.each do |quote_category| %>
          <%= form.fields_for :quote_categories, quote_category do |qc| %>
            <div class="quote-category row mb-2">
            <div class="col-auto">
              <%= qc.label :category_id, "Category", class: "form-label d-inline-block me-2" %>
              <%= qc.select :category_id, Category.all.collect {|cat| [cat.categoryName, cat.id]}, {include_blank: true}, class: "form-control d-inline-block" %>
            </div>
            <div class="col-auto align-self-end">
              <%= link_to '[-] Remove this category', '#', class: 'remove-category', style: "color: red; text-decoration: none;" %>
            </div>
            </div>
          <% end %>
        <% end %>
    </div>


    <!-- submit button -->
    <div class="mt-3">
      <%= form.submit 'Create Quote', class: 'btn btn-primary btn-lg' %>
    </div>
  <% end %>

    <!-- javascript to drive the quote category handling -->
    <script>
    document.addEventListener("DOMContentLoaded", function() {
      document.addEventListener('click', function(e) {
        if (e.target && e.target.classList.contains('remove-category')) {
          e.preventDefault();
          const categoryFields = document.querySelectorAll('.category-field');
          if (categoryFields.length > 1) {
            e.target.closest('.category-field').remove();
          }
        }
      });
    });
    </script>
<% end %>










  

app/views/quotes/_quote.html.erb
<div id="<%= dom_id quote %>">
  <p>
    <strong>Quote:</strong>
    <%= quote.quoteText %>
  </p>

  <p>
    <strong>Year Published:</strong>
    <%= quote.yearOfPublication %>
  </p>

  <p>
    <strong>Comment:</strong>
    <%= quote.comment %>
  </p>

  <p>
    <strong>Is Quote Public?:</strong>
    <%= quote.isQuotePublic %>
  </p>


</div>

app/views/quotes/edit.html.erb
<h1>Editing quote</h1>

<%= render "form", quote: @quote %>

<br>

<div>
  <%= link_to "Show this quote", @quote %> |
  <%= link_to "Back to quotes", quotes_path %>
</div>

app/views/quotes/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Manage Your Quotes</h1>

<div id="quotes">
  <% @quotes.each do |quote| %>
    <%= render quote %>
    <p>
      <%= link_to "Show this quote", quote %>
    </p>
  <% end %>
</div>

<%= link_to "New quote", new_quote_path %>

app/views/quotes/new.html.erb
<h1>New quote</h1>

<%= render "form", quote: @quote %>

app/views/quotes/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @quote %>

<div>
  <%= link_to "Edit this quote", edit_quote_path(@quote) %> |
  <%= link_to "Back to quotes", quotes_path %>

  <div style="padding-top: 20px;">
    <%= button_to "Delete Quote", @quote, method: :delete, class: 'btn btn-danger' %>
  </div>
</div>