config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get '/about', to: 'about#index'
  get '/search', to: "search#index"
  
  get '/admin', to: 'home#aindex'
  get '/userhome', to: 'home#uindex'
  get '/your-quotes', to: 'home#uquotes'

  # session routes
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :quote_categories
  resources :quotes
  resources :authors
  resources :categories
  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

end

app/views/layouts/_header.html.erb
<!-- navigation menu -->
<nav class="navbar bg-dark border-bottom border-body navbar-expand-lg bg-body-tertiary" data-bs-theme="dark">
  <div class="container-fluid">
    <!-- <a class="navbar-brand" href="#">RB Home</a> -->
    
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
        <%= link_to "Home", root_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
        <li><a class="nav-link" href="/search">Search</a></li>
        </li>
        <li class="nav-item">
        <%= link_to "About", about_path, class:"nav-link" %>
        </li>
        <% if !logged_in? %>
          <li class="nav-item">
          <li><%= link_to 'Sign Up', new_user_path, class:"nav-link" %></li>
          </li>
        <% end %>
        <% if !logged_in? %>
          <li class="nav-item">
          <li><%= link_to 'Sign in', login_path, class:"nav-link" %></li>
          </li>
        <% end %>
        <% if logged_in? %>
          <li class="nav-item">
          <%= button_to "Sign Out", logout_path, method: :delete, class:"btn btn-link nav-link" %>
          </li>
        <% end %>
        <% if logged_in? && !is_administrator? %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            User
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to "My Account", userhome_path, class:"dropdown-item" %></li>
            <li><%= link_to "My Quotes", your_quotes_path, class:"dropdown-item" %></li>
            <li><%= link_to "Manage Quotes", quotes_path, class:"dropdown-item" %></li>
            <li><hr class="dropdown-divider"></li>
            <li><%= link_to "Add New Quote", new_quote_path, class:"dropdown-item" %></li>
            <li><%= link_to "Add New Author", new_author_path, class:"dropdown-item" %></li>
          </ul>
        </li>
        <% end %>
        <% if logged_in? && is_administrator? %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Admin
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to "Admin Home", admin_path, class:"dropdown-item" %></li>
            <li><%= link_to 'Manage Users', users_path, class:"dropdown-item" %></li>
            <li><%= link_to 'Manage Authors', authors_path, class:"dropdown-item" %></li>
          </ul>
        </li>
        <% end %>

        <!--
        <li class="nav-item">
          <a class="nav-link disabled" aria-disabled="true">Disabled</a>
        </li>
        -->
      </ul>
      <!--
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
      -->
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myquote</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

    # <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    # <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="container" style="margin-top:20px;">
    <%= render 'layouts/header' %>
      <%= yield %>
    </div>
  </body>
</html>